#!/usr/bin/env node
/**
 * SBOM generator (S01 tasks 2.5 / 2.6).
 *
 * Reads `bun.lock` and `Cargo.lock` and emits `SBOM.md`, grouped into code
 * dependencies, fonts/assets, and codecs.
 *
 * It also *asserts* that the known upstream metadata defects are still present
 * and unrepaired. Recording them as prose would rot the moment someone "tidied"
 * one; checking them means the SBOM cannot silently describe a repository that
 * no longer exists.
 *
 * Four were known before this Slice (task 2.6); a fifth was found during it and
 * is rendered under its own heading rather than merged into the original set.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, statSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(REPO_ROOT, p), "utf8");

/** bun.lock is JSONC with trailing commas. */
function parseBunLock() {
	const raw = read("bun.lock");
	return JSON.parse(raw.replace(/,(\s*[}\]])/g, "$1"));
}

const lock = parseBunLock();
const rootPkg = JSON.parse(read("package.json"));
const webPkg = JSON.parse(read("apps/web/package.json"));

const resolvedPackages = Object.keys(lock.packages ?? {});
const workspaceNames = Object.keys(lock.workspaces ?? {});

/**
 * Curated classification. Only packages that carry non-obvious licensing or
 * media-format weight are pulled out of the general "code" bucket; everything
 * else stays code. Keeping the curation in one visible list means a reviewer can
 * argue with it.
 */
const CODEC_AND_MEDIA = {
	mediabunny: "MP4/WebM/MKV muxing and demuxing, and codec configuration for import and export.",
	soundtouchjs: "Time-stretch and pitch-shift for audio playback.",
	"wavesurfer.js": "Audio waveform decode and display.",
	"opencut-wasm": "The editor's Rust core compiled to WebAssembly: time math, compositor, effects, masks, GPU renderer.",
	"@huggingface/transformers": "In-browser speech-to-text model runtime. Downloads models from Hugging Face at first use.",
	sharp: "Build-time image encoding (also Next's image optimizer backend).",
	"@napi-rs/canvas": "Build-time raster canvas used by the font-sprite generator.",
};

const FONT_AND_ASSET_DEPS = {
	"next/font (Inter)": "Site font for the Next shell, self-hosted by Next at build time. SIL OFL 1.1.",
	"@hugeicons/core-free-icons": "Icon set used across the editor chrome.",
	"lucide-react": "Icon set (ISC).",
	"react-icons": "Icon set aggregator (MIT; individual icon sets carry their own licences).",
	"@tailwindcss/typography": "Prose styles for blog/site surfaces.",
	"tailwindcss-animate": "Animation utilities.",
};

/** Runtime assets shipped from `apps/web/public`, with provenance. */
const RUNTIME_ASSETS = [
	{
		path: "public/fonts/font-atlas.json + font-chunk-*.avif",
		provenance:
			"Generated by `apps/web/scripts/generate-font-sprites.ts` from Google Fonts metadata. The rendered glyph sprites are derived from the Google Fonts corpus, which is distributed under SIL OFL 1.1 / Apache 2.0 per family.",
		fetchedFrom: "`/fonts/...` at runtime by `src/fonts/google-fonts.ts`",
	},
	{
		path: "public/flags/*.svg",
		provenance:
			"Country flag SVGs. Flag designs are not themselves copyrightable in most jurisdictions; the SVG set ships with the upstream repository under its MIT licence.",
		fetchedFrom: "`/flags/<code>.svg` at runtime by `src/stickers/providers/flags.ts`",
	},
	{
		path: "public/effects/preview.jpg",
		provenance: "Upstream-authored effect preview still.",
		fetchedFrom: "`/effects/preview.jpg` by `src/services/renderer/effect-preview.ts`",
	},
	{
		path: "public/logos/opencut/**",
		provenance: "Upstream OpenCut brand marks. Trademark, not covered by the MIT code grant.",
		fetchedFrom: "`/logos/opencut/svg/logo.svg` via `src/site/brand.ts`",
	},
];

/**
 * Known upstream metadata defects. Each carries a probe that must return true —
 * i.e. the defect is still present and unrepaired.
 *
 * D-1..D-4 were known before this Slice began and are enumerated by task 2.6.
 * Anything with `discoveredDuringS01: true` was found while doing the work and
 * is rendered separately, so the pre-known set stays exactly as the task
 * specified it and the new observation is not silently folded in.
 */
const UPSTREAM_DEFECTS = [
	{
		id: "D-1",
		title: "Root `package.json` declares a self-dependency `\"opencut\": \".\"`",
		verbatim: '"opencut": "."',
		detail:
			"The root package (itself named `opencut`) lists itself as a dependency resolving to the repository root. bun installs it as a symlink to the repo root inside `node_modules`.",
		probe: () => rootPkg.dependencies?.opencut === ".",
	},
	{
		id: "D-2",
		title: "Root `package.json` declares application dependencies `next` and `better-auth`",
		verbatim: '"better-auth": "^1.4.15",\n"next": "^16.1.3"',
		detail:
			"These belong to `apps/web`, which declares its own (exact) `next` pin. The root's caret range floats independently, so the lockfile resolves two different `next` versions and installs a nested copy under `apps/web/node_modules`. This is the direct cause of the dual-`next` type identity clash recorded as patch P-001.",
		probe: () =>
			typeof rootPkg.dependencies?.next === "string" &&
			typeof rootPkg.dependencies?.["better-auth"] === "string",
	},
	{
		id: "D-3",
		title: "`rust/wasm/Cargo.toml` `repository` points at a nonexistent GitHub repository",
		verbatim: 'repository = "https://github.com/opencut/opencut"',
		detail:
			"The real upstream is `OpenCut-app/opencut-classic`. The stale URL is republished in the `opencut-wasm` npm package metadata.",
		probe: () => read("rust/wasm/Cargo.toml").includes('repository = "https://github.com/opencut/opencut"'),
	},
	{
		id: "D-4",
		title: "Published `opencut-wasm` declares `sideEffects` on a nonexistent `./snippets/*`",
		verbatim: '"sideEffects": ["./opencut_wasm.js", "./snippets/*"]',
		detail:
			"**Generated, not a publishing accident.** The rebuild-correspondence check (`UPSTREAM.md` § WASM rebuild correspondence) rebuilt this package from `rust/` and got a `package.json` that is *byte-identical* to the published one — which establishes that wasm-pack emits this `sideEffects` entry on every build, rather than it having been introduced when the package was packed. The package's `files` list ships no `snippets/` directory. Harmless — bundlers treat an unmatched glob as an empty set — but it means the published metadata does not describe the published contents, and it will keep doing so for any future build.",
		probe: () => {
			const pkg = JSON.parse(read("node_modules/opencut-wasm/package.json"));
			return (
				Array.isArray(pkg.sideEffects) &&
				pkg.sideEffects.includes("./snippets/*") &&
				!existsInPackage("node_modules/opencut-wasm/snippets")
			);
		},
	},
	{
		id: "D-5",
		discoveredDuringS01: true,
		title: "`rust/wasm` declares `license = \"MIT\"` but ships no LICENSE file",
		verbatim: 'license = "MIT"',
		detail:
			"`rust/wasm/Cargo.toml` declares the MIT licence, but neither `rust/wasm/` nor the published `opencut-wasm` npm package contains a LICENSE file — the published tarball holds only `opencut_wasm{.d.ts,.js,_bg.js,_bg.wasm}`, `package.json` and `README.md`. wasm-pack warns about this on **every** build (`License key is set in Cargo.toml but no LICENSE file(s) were found`).\n\n**Recorded only — deliberately not fixed.** It has zero effect on this Slice's distributable graph, because S01 consumes the *published* package and the repository-root MIT `LICENSE` covers the source. It becomes a genuine release-gate defect at S02, when building the wasm from source becomes the canonical path and the built package would be redistributed without its licence text.",
		probe: () => {
			const declaresMit = read("rust/wasm/Cargo.toml").includes('license = "MIT"');
			const crateLicense = ["LICENSE", "LICENSE.md", "LICENSE-MIT", "COPYING"].some((name) =>
				existsInPackage(`rust/wasm/${name}`),
			);
			const publishedLicense = ["LICENSE", "LICENSE.md", "LICENSE-MIT", "COPYING"].some((name) =>
				existsInPackage(`node_modules/opencut-wasm/${name}`),
			);
			return declaresMit && !crateLicense && !publishedLicense;
		},
	},
];

function existsInPackage(rel) {
	try {
		statSync(join(REPO_ROOT, rel));
		return true;
	} catch {
		return false;
	}
}

function renderDefects(entries) {
	return entries
		.map(
			(d) => `#### ${d.id} — ${d.title}

\`\`\`
${d.verbatim}
\`\`\`

${d.detail}

Still present and unrepaired: **${d.present ? "yes" : `NO — ${d.error ?? "probe returned false"}`}**`,
		)
		.join("\n\n");
}

const defectResults = UPSTREAM_DEFECTS.map((d) => {
	let present = false;
	let error = null;
	try {
		present = d.probe();
	} catch (e) {
		error = e.message;
	}
	return { ...d, present, error };
});

// --- Rust ---------------------------------------------------------------
function cargoCrates(target) {
	const out = execFileSync(
		"cargo",
		[
			"tree", "-p", "opencut-wasm", "--offline", "--edges", "normal",
			"--prefix", "none", "--target", target,
		],
		{ cwd: REPO_ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
	);
	return [
		...new Set(
			out
				.split("\n")
				.map((l) => l.replace(/ \(proc-macro\)/, "").replace(/ \(\*\)$/, "").replace(/ \(.*\)$/, "").trim())
				.filter(Boolean),
		),
	].sort();
}

let wasmCrates = [];
let cargoError = null;
try {
	wasmCrates = cargoCrates("wasm32-unknown-unknown");
} catch (e) {
	cargoError = e.message;
}

const cargoLockCrateCount = (read("Cargo.lock").match(/^name = /gm) ?? []).length;

// --- assemble -----------------------------------------------------------
const depTable = (deps) =>
	Object.entries(deps ?? {})
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([name, range]) => `| \`${name}\` | \`${range}\` |`)
		.join("\n");

const publicDirs = readdirSync(join(REPO_ROOT, "apps/web/public"));

const md = `# SBOM — software bill of materials

Generated by \`script/generate-sbom.mjs\` from \`bun.lock\` and \`Cargo.lock\`. Regenerate with:

\`\`\`
node script/generate-sbom.mjs
\`\`\`

Upstream pin: \`cf5e79e919144200294fb9fed22a222592a0aeea\` (see [\`UPSTREAM.md\`](UPSTREAM.md)).
Per-file content hashes of the inherited source are in [\`SOURCE_INVENTORY.md\`](SOURCE_INVENTORY.md).

## Totals

| Ecosystem | Count | Source |
| --- | ---: | --- |
| npm packages resolved | ${resolvedPackages.length} | \`bun.lock\` |
| bun workspace members | ${workspaceNames.length} | \`bun.lock\` (\`${workspaceNames.map((w) => w || "<root>").join("\`, \`")}\`) |
| Rust crates in the workspace lockfile | ${cargoLockCrateCount} | \`Cargo.lock\` (includes \`apps/desktop\`'s \`gpui\` graph, which is **not** built for wasm) |
| Rust crates in the \`opencut-wasm\` wasm32 graph | ${wasmCrates.length} | \`cargo tree -p opencut-wasm --target wasm32-unknown-unknown\` |

\`apps/desktop\` has no \`package.json\`, so it is a Cargo workspace member only and is not a bun
workspace member despite the \`apps/*\` glob. It is excluded from the distributable graph entirely.

## 1. Code dependencies

### Root \`package.json\` — direct dependencies

| Package | Range |
| --- | --- |
${depTable(rootPkg.dependencies)}

### Root \`package.json\` — direct devDependencies

| Package | Range |
| --- | --- |
${depTable(rootPkg.devDependencies)}

### \`apps/web\` — direct dependencies

| Package | Range |
| --- | --- |
${depTable(webPkg.dependencies)}

### \`apps/web\` — direct devDependencies

| Package | Range |
| --- | --- |
${depTable(webPkg.devDependencies)}

### Rust crates in the wasm32 build graph

${
	cargoError
		? `> Could not resolve the crate graph: ${cargoError}`
		: `${wasmCrates.length} crates. First-party crates are \`opencut-wasm\`, \`bridge\`, \`compositor\`, \`effects\`, \`gpu\`, \`masks\` and \`time\` (in \`rust/\`); the rest are third-party.\n\n${wasmCrates.map((c) => `- \`${c}\``).join("\n")}`
}

## 2. Fonts and assets

### Dependencies that ship glyphs or icon artwork

| Package | Role |
| --- | --- |
${Object.entries(FONT_AND_ASSET_DEPS).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")}

### Runtime assets served from \`apps/web/public\`

Present directories: ${publicDirs.map((d) => `\`${d}\``).join(", ")}.

| Asset | Provenance | Fetched from |
| --- | --- | --- |
${RUNTIME_ASSETS.map((a) => `| \`${a.path}\` | ${a.provenance} | ${a.fetchedFrom} |`).join("\n")}

The Vite example copies a deliberate subset of these by allowlist rather than shipping all of
\`public/\`; that allowlist is emitted as the runtime asset manifest (design D7).

## 3. Codecs and media runtimes

| Package | Role |
| --- | --- |
${Object.entries(CODEC_AND_MEDIA).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")}

Video and audio decoding otherwise relies on the browser's own WebCodecs and Media Source
implementations; no codec binaries are vendored into this repository. GPU rendering goes through
\`wgpu\`/\`naga\` compiled into \`opencut-wasm\`, targeting WebGPU with a WebGL fallback.

## 4. Known upstream metadata defects — recorded, **not** repaired

These are defects in the pinned upstream's own metadata. Repairing them would be an unlogged
behavioural change to the baseline this Slice exists to compare against, so they are recorded and
left in place (design D5). The boundary checks operate on the emitted module graph, so a
declared-but-unimported package cannot make them pass or fail incorrectly.

Each entry below is verified still present by this generator; if one is ever repaired, regenerating
this file fails loudly instead of quietly describing a repository that no longer exists.

### Known before this Slice began

${renderDefects(defectResults.filter((d) => !d.discoveredDuringS01))}

### Discovered during S01

Kept separate from the four above so the pre-known set stays exactly as it was enumerated, and so a
reader can tell what this work found from what it inherited.

${renderDefects(defectResults.filter((d) => d.discoveredDuringS01))}
`;

writeFileSync(join(REPO_ROOT, "SBOM.md"), md);

console.log(`SBOM: ${resolvedPackages.length} npm packages, ${wasmCrates.length} wasm crates`);
for (const d of defectResults) {
	console.log(`  ${d.present ? "present" : "MISSING"}  ${d.id} — ${d.title}`);
}

const repaired = defectResults.filter((d) => !d.present);
if (repaired.length > 0) {
	console.error(
		`\n${repaired.length} documented upstream defect(s) no longer detected. Either the repository was ` +
			`repaired (which must be patch-logged and the SBOM text updated) or the probe is stale.`,
	);
	process.exit(1);
}
